package koneksi;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class penjualan extends javax.swing.JFrame {

    /**
     * Creates new form penjualan
     */


    public penjualan() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkursi = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbojurusan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbojenis = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ONLINE AIRPLANES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Seat ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Total Ticket");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Total Payment");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        txtkursi.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txtkursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 120, -1));

        txtnama.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 190, -1));

        txtjumlah.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });
        jPanel1.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Goes To");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        cbojurusan.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbojurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here", "Changi Intl, Singapore", "Heathrow, London", "Incheon Intl, Seoul", " " }));
        cbojurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbojurusanActionPerformed(evt);
            }
        });
        jPanel1.add(cbojurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("Prices");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        txtharga.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Rp.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 60, -1));

        jButton4.setBackground(new java.awt.Color(255, 170, 170));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 102));
        jLabel10.setText("Payment");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        txtbayar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 102));
        jLabel11.setText("Change");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        txtkembalian.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 102));
        jLabel12.setText("Type of Ticket");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        cbojenis.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cbojenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Here", "(Changi Intl, Singapore) VIP", "(Changi Intl, Singapore) Economic", "(Heathrow, London) VIP", "(Heathrow, London) Economic", "(Incheon Intl, Seoul) VIP", "(Incheon Intl, Seoul) Economic" }));
        cbojenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbojenisActionPerformed(evt);
            }
        });
        jPanel1.add(cbojenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, -1));

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        jButton2.setText("Print Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 690, 230));

        jTextField1.setBackground(new java.awt.Color(38, 153, 153));
        jTextField1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("                                            TICKETING");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 80));

        txttotal.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void cbojurusanActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        // daftar harga sesuai jurusan
    if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Changi Intl, Singapore")) {
    }else if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Heathrow, London")) {
    }
    else if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Incheon Intl, Seoul")) {
    }

    }                                          

    private void cbojenisActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Changi Intl, Singapore) VIP")) {
        txtharga.setText("5000000");
    } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Changi Intl, Singapore) Economic")) {
        txtharga.setText("2000000");
    } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Heathrow, London) VIP")) {
        txtharga.setText("15000000");
    } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Heathrow, London) Economic")) {
        txtharga.setText("11000000");
    } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Incheon Intl, Seoul) VIP")) {
        txtharga.setText("13000000");
    } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Incheon Intl, Seoul) Economic")) {
        txtharga.setText("9000000");
    } 
    }                                        

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txtharga.getText());
        b=Integer.valueOf(txtjumlah.getText());
        c=a*b;
        txttotal.setText(""+c);
    }                                     

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txtbayar.getText());
        b=Integer.valueOf(txttotal.getText());
        c=a-b;
        txtkembalian.setText(""+c);
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    try {
        String sql = "INSERT INTO tbuas VALUES ('" + txtkursi.getText()
                + "','" + txtnama.getText()
                + "','" + txtjumlah.getText()
                + "','" + txttotal.getText()
                + "','" + txtbayar.getText()
                + "','" + txtkembalian.getText()
                + "','" + cbojurusan.getSelectedItem()
                + "','" + cbojenis.getSelectedItem()
                + "','" + txtharga.getText()+ "')";
        java.sql.Connection conn = (Connection) koneksi.configDB();
        java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null, "Your Data Process is Success");
  
        } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null,"Are your sure you want to leave this page?","Exit",JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION)
        {
        dispose();
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         jButton2.setText((String)cbojurusan.getSelectedItem());
        txt_area.setText(
        "                                                                              ONLINE AIRPLANES TICKETING "+"\n"+
        "______________________________________________________________________________________________ "+"\n"+"\n"+
        
        "                                                   Seat ID                                                           :   "+txtkursi.getText()+"\n"+
        "                                                   Name                                                             :   "+txtnama.getText()+"\n"+
        "                                                   Goes To                                                         :   "+cbojurusan.getSelectedItem()+"\n"+
        "                                                   Type of Ticket                                                :   "+cbojenis.getSelectedItem()+"\n"+
        "                                                   Total Ticket                                                    :   "+txtjumlah.getText()+"\n"+
        "                                                   Price                                                               :   "+txtharga.getText()+"\n"+
        "                                                   Total Payment                                              :   "+txttotal.getText()+"\n"+
        "                                                   Payment                                                        :   "+txtbayar.getText()+"\n"+
        "                                                   Change                                                         :   "+txtkembalian.getText()+"\n");

    }                                        

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cbojenis;
    private javax.swing.JComboBox<String> cbojurusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtkursi;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttotal;
    // End of variables declaration                   

   
